Azure-Samples/azure-ai-vision-sdk

- README.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> coming soon

- README.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> for better visibility in the samples browser

- docs/learn.microsoft.com/python/image-analysis/2/main.py
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix snippet tag

- README.md
> Samples browser fix

- GET_FACE_ARTIFACTS_ACCESS.md
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Revise readme files

- README.md
- samples/kotlin/face/FaceAnalyzerSample/README.md
- samples/swift/face/FaceAnalyzerSample/README.md
Adding Face SDK documentation references.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
> Add SDK document references.

- GET_FACE_ARTIFACTS_ACCESS.md
- docs/face/android_api_reference.md
- docs/face/ios_api_reference.md
- samples/kotlin/face/FaceAnalyzerSample/README.md
- samples/swift/face/FaceAnalyzerSample/README.md
Adding face api reference docs
``
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
``'
> Adding api reference docs

- GET_FACE_ARTIFACTS_ACCESS.md
* Swaps the order of query and generate key instructions
* Links to relevant concepts
* Puts subscription id as script parameter for error-proofing
* Adds info box to warn about token regeneration
* Points to Android/iOS page where the tokens can be used next
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
*  Read the code
* Preview the markdown
> Improves GET_FACE_ARTIFACTS_ACCESS.md

- GET_FACE_ARTIFACTS_ACCESS.md
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
*  Read the code
```
```
* Preview
> fixes artifacts script

- samples/swift/face/FaceAnalyzerSample/README.md
* adds SwiftPM instructions with system Git
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
*  Read the code
* Preview Markdown
> adds SwiftPM instructions with system Git

- GET_FACE_ARTIFACTS_ACCESS.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> updates artifacts instruction regarding permissions

- GET_FACE_ARTIFACTS_ACCESS.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fixes artifacts instruction regarding permissions

- samples/kotlin/face/FaceAnalyzerSample/README.md
- samples/kotlin/face/FaceAnalyzerSample/app/build.gradle
- samples/kotlin/face/FaceAnalyzerSample/app/src/main/AndroidManifest.xml
- samples/kotlin/face/FaceAnalyzerSample/app/src/main/java/com/example/FaceAnalyzerSample/AnalyzeActivity.kt
- samples/kotlin/face/FaceAnalyzerSample/app/src/main/java/com/example/FaceAnalyzerSample/AutoFitSurfaceView.kt
- samples/kotlin/face/FaceAnalyzerSample/app/src/main/java/com/example/FaceAnalyzerSample/MainActivity.kt
- samples/kotlin/face/FaceAnalyzerSample/build.gradle
- samples/swift/face/FaceAnalyzerSample/FaceAnalyzerSample/Core/LivenessActor.swift
- samples/swift/face/FaceAnalyzerSample/README.md
* updates samples for 0.16.3-beta.3
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* Read the code
> updates samples for 0.16.3-beta.3

- samples/javascript/README.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fixing readme link

- samples/nextjs/README.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix setup-env file link

- samples/kotlin/face/FaceAnalyzerSample/app/build.gradle
A default HttpClient implementation should be added to build.gradle, or there will be an issue `A request was made to load the default HttpClient provider but one could not be found on the classpath. If you are using a dependency manager, consider including a dependency on azure-core-http-okhttp or azure-core-http-httpurlconnection. Depending on your existing dependencies, you have the choice of OkHttp or HttpUrlConnection implementations. Additionally, refer to https://aka.ms/azsdk/java/docs/custom-httpclient to learn about writing your own implementation.`
Make the kotlin demo run successfully.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, …
```
> Add default HttpClient to app/build.gradle

- README.md
- samples/swift/face/FaceAnalyzerSample/README.md
update swift sample README doc for AzureAIVisionFace.xcframework and AzureAIVsionCore.xcframework downloading issue.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> update swift readme doc

- samples/web/README.md
- samples/web/angularjs/.gitignore
- samples/web/angularjs/angular.json
- samples/web/angularjs/server.js
- samples/web/nextjs/.gitignore
- samples/web/nextjs/components/FaceAnalyzerSampleClient.tsx
- samples/web/nextjs/middleware.js
- samples/web/vuejs/.gitignore
- samples/web/vuejs/server.js
Update Web samples to remove CORS headers
* ...
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
> Update Web samples to remove CORS headers

- scripts/get_face_access_token.ps1
- scripts/get_face_access_token.sh
Update script to fetch token to login to azure if needed
* ...
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
> Update script to fetch token to login to azure if needed

- samples/kotlin/face/FaceLivenessDetectorSample/app/build.gradle.kts
Update artifact version to 1.1.0
> Update artifact version to 1.1.0

- README.md
Fix readme sdk reference links.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix readme sdk reference links
